# Generated by Django 5.0.7 on 2024-07-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryapp', '0002_category_task_due_date_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
