# Generated by Django 5.0.7 on 2024-07-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryapp', '0003_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
